"""create db

Revision ID: 37e7d9d5034a
Revises: 
Create Date: 2021-05-27 01:10:44.422991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e7d9d5034a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('law',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_title'), 'law', ['title'], unique=False)
    op.create_table('law_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_law', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['id_law'], ['law.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_part_title'), 'law_part', ['title'], unique=False)
    op.create_table('law_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_part', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['id_part'], ['law_part.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_section_name'), 'law_section', ['name'], unique=False)
    op.create_table('law_chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_section', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['id_section'], ['law_section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_chapter_name'), 'law_chapter', ['name'], unique=False)
    op.create_table('law_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_chapter', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('text', sa.Text(length=65000), nullable=False),
    sa.ForeignKeyConstraint(['id_chapter'], ['law_chapter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('law_article')
    op.drop_index(op.f('ix_law_chapter_name'), table_name='law_chapter')
    op.drop_table('law_chapter')
    op.drop_index(op.f('ix_law_section_name'), table_name='law_section')
    op.drop_table('law_section')
    op.drop_index(op.f('ix_law_part_title'), table_name='law_part')
    op.drop_table('law_part')
    op.drop_index(op.f('ix_law_title'), table_name='law')
    op.drop_table('law')
    # ### end Alembic commands ###
