"""create base tables

Revision ID: f36a948dc2ea
Revises: 
Create Date: 2021-05-25 17:06:40.180406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f36a948dc2ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('law',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_title'), 'law', ['title'], unique=False)
    op.create_table('law_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_law', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['id_law'], ['law.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_section_name'), 'law_section', ['name'], unique=False)
    op.create_table('law_chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_section', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['id_section'], ['law_section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_chapter_name'), 'law_chapter', ['name'], unique=False)
    op.create_table('law_paragraph',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_chapter', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['id_chapter'], ['law_chapter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_paragraph_name'), 'law_paragraph', ['name'], unique=False)
    op.create_table('law_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_paragraph', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('text', sa.Text(length=65000), nullable=False),
    sa.ForeignKeyConstraint(['id_paragraph'], ['law_paragraph.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_article_name'), 'law_article', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_law_article_name'), table_name='law_article')
    op.drop_table('law_article')
    op.drop_index(op.f('ix_law_paragraph_name'), table_name='law_paragraph')
    op.drop_table('law_paragraph')
    op.drop_index(op.f('ix_law_chapter_name'), table_name='law_chapter')
    op.drop_table('law_chapter')
    op.drop_index(op.f('ix_law_section_name'), table_name='law_section')
    op.drop_table('law_section')
    op.drop_index(op.f('ix_law_title'), table_name='law')
    op.drop_table('law')
    # ### end Alembic commands ###
